### ISSUE TITLE
failed to bring it up because panic error

### ISSUE THREAD

**Issue by gaowayne** [cubefs/cubefs-dashboard#38]
this is my yml file
```
# permissions and limitations under the License.

server:
  port: 6007
  mode: dev
  static_resource:
    enable: true
    relative_path: /portal
    root_path: ./dist
prefix:
  api: /api/cubefs
mysql:
  host: "localhost"
  port: 3306
  slaveHost:
  slavePort:
  user: "your_user"
  password: "your_password"
  database: "cubefs"
  maxIdleConn: 20
  MaxOpenConn: 300
```
this is panic error log
```
root@salab-bncbeta03:~/wayne/cubefs/cubefs-dashboard/bin# ./cfs-gui -c config.yml
panic: illegal base64 data at input byte 4

goroutine 1 [running]:
github.com/cubefs/cubefs-dashboard/backend/helper.Must({0x104bb40?, 0x15682e0?}, {0x0?, 0xc0020f1f70?, 0x407e79?})
        /root/wayne/cubefs/cubefs-dashboard/backend/helper/helper.go:37 +0x22e
main.main()
        /root/wayne/cubefs/cubefs-dashboard/backend/main.go:45 +0x145
```
